name: Run main.py every 2 minutes

on:
  schedule:
    - cron: '*/2 * * * *'  # Läuft alle 2 Minuten
  workflow_dispatch:  # Manuelles Starten erlaubt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installiert nur yfinance und andere Pakete

      - name: Execute Python Script
        run: python test.py  # Führt das Skript aus

      # Der Commit- und Push-Schritt wird entfernt, da keine Änderungen ins Repo geschrieben werden.
